### ISSUE TITLE
Basic meny 8h

### ISSUE THREAD

**Issue by PontusF** [wuxxerno/Hi-Lo-Quiz#12]

**Comment by wuxxerno** [comment]
status update: basic version pushed to branch robin

**Comment by AdamBremholm** [comment]
Suggestion: Could we move Menu from Home.vue to App.vue above router-view? Or is there some instance in the game where we don't want to show the menu?

**Comment by wuxxerno** [comment]
I only see benefits with your suggested change. You have my vote.  @AdamBremholm
