### ISSUE TITLE
Rest Api 40h

### ISSUE THREAD

**Issue by AdamBremholm** [wuxxerno/Hi-Lo-Quiz#2]

**Comment by vargen2** [comment]
# backend

Alla reviewed
question {
  id: string,
  usersubmitted: bool,
  author: string,
  category: string,
  reviewedby: string,
  question: string,
  imageurl: string,
  answer: number,
  low: number,
  high: number
}

alla unreviewd
samma + {
  status: approved/notapproved
}


- /api/questions/ GET
- /api/questions/ POST (bara admin)
- /api/questions?amount=10 GET
- /api/questions/:id GET
- /api/questions/:id PUT
- /api/questions/:id DELETE
- /api/questions/category/sport?amount=10 GET
- /api/questions/author/:author GET

- /api/questions/unreviewed/ GET (bara admin se)
- /api/questions/unreviewed/ POST (alla)

**Comment by vargen2** [comment]
Lite grejer vi har kvar att göra
https://stackoverflow.com/questions/39277670/how-to-find-random-record-in-mongoose
https://mongoosejs.com/docs/validation.html
https://expressjs.com/en/guide/error-handling.html

**Comment by ljungberg84** [comment]
Toppen. 
Kanske sitter lite i morgon om jag får feeling och då kan jag ha det som utgångspunkt.

**Comment by vargen2** [comment]
### Back end

- Fixa att password lagras hashat
- Collection för users
- create user
- remove user

```
User {
  "name": string,
  "displayName": string, (kanske kan vara bra)
  "password": string,
  "isAdmin": bool
}

```


### Front end

- html get login page
- html post till login

- page create user

- page att add questions
  - Ej inloggade kan också adda, men blir approved=false, author=Guest

- page for inloggad admin där man kan 
  -	approve questions
  -	delete questions

**Comment by Peteropon** [comment]
Jag börjar greja med login page
