### ISSUE TITLE
Bestäm hur spelet hanterar time limits för spelare

### ISSUE THREAD

**Issue by PontusF** [wuxxerno/Hi-Lo-Quiz#21]
Förslag 1: bestämd gratis tid varje tur +spelarbuffert.

Förslag 2: Spelartid som alltid tickar ner när det är en spelares tur

**Comment by vargen2** [comment]
Lägg till stöd för båda. Så kan vi speltesta sedan och kanske välja ett eller ha kvar båda som options.
