### ISSUE TITLE
Välja databas 8h

### ISSUE THREAD

**Issue by AdamBremholm** [wuxxerno/Hi-Lo-Quiz#5]

**Comment by vargen2** [comment]
Kollade runt lite. Detta verkar bra. 
https://www.mongodb.com/cloud/atlas
Man kan hosta databas där gratis

**Comment by vargen2** [comment]
Inget credit card required

**Comment by AdamBremholm** [comment]
Vi körde den på springlabben och hostning där fungerade bra!

Den tors 9 maj 2019 10:10hjalmar <notifications@github.com> skrev:

**Comment by ljungberg84** [comment]
nice, ser ju lovande ut:)
